module.exports = {
    testMatch: [
        "**/test/**/*.js"
    ],
    moduleFileExtensions: ['js'],
    transform: {
        '^.+\\.js$': './jest-transform.js',
    },
    transformIgnorePatterns: [
        // transform ES6 modules generated by BuckleScript
        // https://regexr.com/46984
        "/node_modules/(?!@glennsl/bs-jest|bs-platform|@rescript|rescript).+\\.js$"
    ],
};